# Generated by Django 4.1.2 on 2022-10-31 23:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saldos', '0002_alter_account_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='salida',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='transaction',
            name='operation',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw')], default='DEPOSIT', max_length=15),
        ),
    ]
