# Generated by Django 4.1.2 on 2022-11-01 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saldos', '0003_remove_transaction_entrada_remove_transaction_salida_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='saldo',
            new_name='balance',
        ),
    ]
